### ISSUE TITLE
Multiple Things Aren't Themed

### ISSUE THREAD

**Issue by doamatto** [imfunniee/gitark#10]
Here's a raw list of things that aren't themed:
- Invite section for Organisations
- Hover on Related Issues
- Busy Status on Drop-down, User's Profile, and User's Badge
- Access to Repos, Teams, and General Info on Organisation's People Page
- Third-Party Access for Organisation Settings
- Recovery Options header on Security settings page
- Articles on the [GitHub Press page](https://github.com/about/press)
- Selected Text and Padding on Customer Stories
- Join Organisation on Profile has odd border

I'd be happy to help do some of these for you and make a PR

---

![image](https://user-images.githubusercontent.com/30969346/57971577-d16f9a80-7944-11e9-85fc-bea69889f562.png)
![image](https://user-images.githubusercontent.com/30969346/57971600-f82dd100-7944-11e9-9795-4050f4316b18.png)
![image](https://user-images.githubusercontent.com/30969346/57971603-02e86600-7945-11e9-858b-d3b44e396d95.png)
![image](https://user-images.githubusercontent.com/30969346/57971616-32976e00-7945-11e9-92d5-b24f69904298.png)
![image](https://user-images.githubusercontent.com/30969346/57971612-27dcd900-7945-11e9-9762-43ed16a57421.png)
![image](https://user-images.githubusercontent.com/30969346/57971620-3a571280-7945-11e9-93e6-3278fbefab44.png)
![image](https://user-images.githubusercontent.com/30969346/57971635-5a86d180-7945-11e9-8821-1deec84ae618.png)
![image](https://user-images.githubusercontent.com/30969346/57971645-7f7b4480-7945-11e9-9301-6e3d432f4905.png)
![image](https://user-images.githubusercontent.com/30969346/57971663-bfdac280-7945-11e9-8815-519b8cdc9116.png)
![image](https://user-images.githubusercontent.com/30969346/57971686-04665e00-7946-11e9-9591-90317470a78f.png)
![image](https://user-images.githubusercontent.com/30969346/57971702-4099be80-7946-11e9-92bf-79d1ed4c86fd.png)

**Comment by imfunniee** [comment]
cool, create a PR and i'll merge it. make sure you keep the themes of these components similar.

**Comment by Atulin** [comment]
Also comment buttons
![image](https://user-images.githubusercontent.com/11233299/64580956-9af0dc00-d388-11e9-99f8-ceb26392da6b.png)
And timeline breaks
![image](https://user-images.githubusercontent.com/11233299/64580973-ae9c4280-d388-11e9-93ce-b59c7fd3f2c1.png)

**Comment by oliszymanski** [comment]
nice nice!
