### ISSUE TITLE
Consider UserCSS distribution

### ISSUE THREAD

**Issue by glc-mvion** [imfunniee/gitark#16]
As a user of [Stylus][stylus], I would love install your theme as UserCSS, it has some benefits over a browser extension.

- It consist of some information in a CSS comment see [Gitlab Dark][glab-dark] by example
- Automatic updates for user since Stylus takes care of it
- Browser extensions may raise certain concerns about security see Gervasio Marchand [article][ext-article] about that.

If you want, I can submit a pull request to add this "magic" comment and add a badge to the README.

[stylus]: https://github.com/openstyles/stylus
[glab-dark]: https://gitlab.com/vednoc/dark-gitlab/raw/master/gitlab.user.styl
[ext-article]: https://g3rv4.com/2018/09/browser-extensions-are-insecure

**Comment by imfunniee** [comment]
sure
