### ISSUE TITLE
How to prevent flash on page load

### ISSUE THREAD

**Issue by miguelmota** [imfunniee/gitark#17]
Cool theme! 

Whenever a page is loaded there is a flash for a second which is when the CSS is being injected I'm assuming. Is there any way that can be improved (load the CSS right away so that there's no visibility from original theme to dark theme)?

**Comment by imfunniee** [comment]
Hey @miguelmota, 
I have fixed the bug in the latest version (v0.1.0), it should be live anytime 😄
