### ISSUE TITLE
It would spend a little time loading dark mode after turning to another pages.

### ISSUE THREAD

**Issue by BigCoke233** [imfunniee/gitark#19]
When I click A tags to turn to another page on GitHub, Gitark will spend a little time loading the dark mode after loading the whole page. Before it finishes its work, the white page is too bright for my tired eyes. I wish you can fix it.

(My English is not good, I hope you can understand it easily.)

**Comment by imfunniee** [comment]
Hey @BigCoke233, 
I have fixed the bug in the latest version (v0.1.0), it should be live anytime 😄
