### ISSUE TITLE
Avatars in homepage need margin.

### ISSUE THREAD

**Issue by VamOSGS** [imfunniee/gitark#20]
I think in activity feed (homepage) avatars looking not  good and will be better if avatar's span element will have margin from left border too.
Now:
![image](https://user-images.githubusercontent.com/26979773/60162978-b3326f80-980b-11e9-8215-ffc44bc1baaa.png)
Need to be:
![image](https://user-images.githubusercontent.com/26979773/60163095-e8d75880-980b-11e9-9697-358d93e4f544.png)

**Comment by imfunniee** [comment]
fixed that in the latest version, lemme know if the bug is still there 😃

**Comment by VamOSGS** [comment]
Bug fixed, everything works fine, Thanks.
