### ISSUE TITLE
Recently pushed branches alert - poor contrast

### ISSUE THREAD

**Issue by DLMousey** [imfunniee/gitark#26]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/8281699/67015715-dcdf1180-f0ee-11e9-9b3b-b7313b1e6cb5.png">

**Comment by joestrong** [comment]
@DLMousey This issue is fixed in the master branch, I've just checked it in Chrome and Firefox. I believe the one on the Firefox add-on store is out of date.

**Comment by DLMousey** [comment]
Firefox store shows 0.1.0, and chrome web store shows 0.0.9. Is it just a case of making another release or is it more of a waiting for the stores to catch up?

**Comment by joestrong** [comment]
I assume @imfunniee would need to update the Firefox store

**Comment by imfunniee** [comment]
@joestrong @DLMousey The firefox one is up to date but the chrome one is a version behind. https://github.com/imfunniee/gitark#download-v010
