### ISSUE TITLE
.pagehead gets overriden

### ISSUE THREAD

**Issue by davidli3100** [imfunniee/gitark#28]
![image](https://user-images.githubusercontent.com/24843957/74998401-a27fdb00-5426-11ea-9f4c-ca9a995d1a22.png)

Not sure what to do about this - tried making a couple of edits to the CSS but for some reason the styling in github's pagehead.scss (line 74) always overrides it.

**Comment by joestrong** [comment]
What branch were you on? I don't see this problem with master
