### ISSUE TITLE
why the firefox addon asks me to access my github data?

### ISSUE THREAD

**Issue by marcomaggi** [imfunniee/gitark#5]
The dark colours look great.  I love dark themes.  But why, when installing the addon from the mozilla site, it asks me permissions to read my github data?

**Comment by imfunniee** [comment]
ye, its necessary to access the "HTML DOM" data for github to change the appearance of the site. Here is a better <a href="https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions">article</a>  explaining the permissions.

**Comment by marcomaggi** [comment]
Thanks.
