### ISSUE TITLE
Code font is not monospaced

### ISSUE THREAD

**Issue by samwaterbury** [imfunniee/gitark#8]
First off, this theme is just awesome and I appreciate the work on it.

However, I am experiencing an issue where source code font is not monospaced. This issue happens for all code on GitHub. Here's a screenshot:

<img width="1230" alt="Screen Shot 2019-05-03 at 6 19 10 PM" src="https://user-images.githubusercontent.com/30158870/57170159-8a27cc80-6dd0-11e9-8fdd-279a90ae2422.png">

I'm not sure if this is a known issue or if it's just me for some reason. It happens even when all other extensions and themes are disabled. This is on Firefox, but I installed it on Chrome and it's happening there too.

**Comment by imfunniee** [comment]
It's github that isn't allowing to load fonts from outside. I'll work on it to make it work somehow 😅 (plus  few places where this addon/extension doesn't work 👀).

**Comment by LoLei** [comment]
This is still happening for me btw.

**Comment by imfunniee** [comment]
@LoLei kinda busy atmost, alot changed on github since the last release, gonna work on it once im free. which browser btw?

**Comment by LoLei** [comment]
@imfunniee It's not that big of a deal, thanks for your work!

It's happening in Firefox (78.0.2) and Chrome (84.0.4147.89) for me, gitark version 0.1. (unpacked ext in chrome)
