### ISSUE TITLE
Add Alpha to the blob code addition and deletion

### ISSUE THREAD

**Issue by Urriel** [imfunniee/gitark#9]
Hello, I would suggest updating the blob-code-addition and blob-code-deletion class with an alpha setting:

![image](https://user-images.githubusercontent.com/5276818/57854819-6f4e5280-77e9-11e9-8390-4dc0e78a87d6.png)

![image](https://user-images.githubusercontent.com/5276818/57854838-7aa17e00-77e9-11e9-8455-38a7e424bac1.png)

**Comment by imfunniee** [comment]
sure will work on that

**Comment by Urriel** [comment]
Thank you.

Your theme is great I love it by the way.

**Comment by imfunniee** [comment]
@Urriel  Added that, plus fixed some bugs in the latest version (v0.1.0), it should be live anytime 😄
